source 'https://rubygems.org'

#Allow use of the "beacon" library, as though it were a gem.
gem 'jd_beacon', :path => './'

#Include any files found in the local gemspec.
gemspec

#Pry debugger.
group :development do

  #Any version of the Pry debugger.
  gem 'pry'
  gem 'awesome_print'

  #And rspec, for unit tests.
  gem 'rspec', '~>2.14.1'
  gem 'guard-rspec', '~>4.2.8'

  #Shotgun, which allows us to restart the development when necessary.
  gem 'shotgun', '~>0.9'

end
