source 'https://rubygems.org'

#bRequire-all, which allows us to easily import whole folders.
gem 'require_all', '~>1.2.1'

#Web front-end libraries.
gem 'sinatra',  '~>1.4.2'
gem 'compass',  '~>0.12.2'
gem 'barista',  '~>1.3.0'
gem 'haml',     '~>4.0.0'

#Allow use of the "beacon" library, as though it were a gem.
gem 'jd_beacon', :path => './'

#Include any files found in the local gemspec.
gemspec

#Pry debugger.
group :development do

  #Any version of the Pry debugger.
  gem 'pry'
  gem 'awesome_print'

  #And rspec, for unit tests.
  gem 'rspec', '~>2.14.1'

  #Shotgun, which allows us to restart the development when necessary.
  gem 'shotgun', '~>0.9'

end
